name: "Upstream Sync"

on:
  schedule:
    - cron: "0 12 * * *" # every day

  workflow_dispatch: # click the button on Github repo!
    inputs:
      sync_test_mode: # Adds a boolean option that appears during manual workflow run for easy test mode config
        description: "Fork Sync Test Mode"
        type: boolean
        default: false

jobs:
  sync_upstream:
    if: github.event.repository.fork
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo
    outputs:
      has_new: ${{ steps.sync.outputs.has_new_commits }}
    steps:
      # Step 1: run a standard checkout action, provided by github
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_SYNC_TOKEN || github.token }}

      # Step 2: run the sync action
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: GeekSnail/edgetunnel
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          git_config_pull_rebase: true
          # Set test_mode true during manual dispatch to run tests instead of the true action!!
          test_mode: ${{ inputs.sync_test_mode }}

      - name: Sync check
        if: failure()
        run: |
          # if git diff --name-only HEAD upstream/main -- .github/workflows | grep .; then
          echo "âš  ä¸Šæ¸¸ä»“åº“çš„ workflow æ–‡ä»¶æœ‰æ›´æ–°" >> $GITHUB_STEP_SUMMARY
          echo "âŒ ç”±äºŽ GitHub é™åˆ¶ï¼Œæ— æ³•è‡ªåŠ¨åŒæ­¥ workflow æ–‡ä»¶" >> $GITHUB_STEP_SUMMARY
          echo "ðŸ‘‰ è¯·å‰å¾€ä»“åº“é¡µï¼Œç‚¹å‡» **Sync fork â†’ Update branch / Discard commits** æ¥æ‰‹åŠ¨æ›´æ–°" >> $GITHUB_STEP_SUMMARY
          exit 1

  deploy:
    needs: sync_upstream
    if: github.event.repository.fork && needs.sync_upstream.outputs.has_new == 'true'
    uses: ./.github/workflows/update_host.yml
    with:
      shouldDeploy: "true"
    secrets: inherit

  workflow-keepalive:
    if: github.event.repository.fork && github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
